## Ghost-Blog container including S3 storage adapter

FROM ghost:3-alpine

WORKDIR /var/lib/ghost

RUN npm install -g ghost-storage-adapter-s3@2.8.0 && \
    ln -s /usr/local/lib/node_modules/ghost-storage-adapter-s3 ./current/core/server/adapters/storage/s3